services:
  - type: web
    name: 3commas-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      # Create SQLite file first
      touch trading_bot.db
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: sqlite:///trading_bot.db  